#ifndef KEYBOARDMATRIX_DEF_H_
#define KEYBOARDMATRIX_DEF_H_

#include "stm32f1xx_hal.h"

// Define số hàng và cột
#define KEYPAD_MAX_ROW      4
#define KEYPAD_MAX_COLUMN   4

// Khai báo các chân GPIO cho hàng (row)
#define KEYPAD_ROW_1_PIN    GPIO_PIN_4
#define KEYPAD_ROW_2_PIN    GPIO_PIN_5
#define KEYPAD_ROW_3_PIN    GPIO_PIN_6
#define KEYPAD_ROW_4_PIN    GPIO_PIN_7

#define KEYPAD_ROW_1_PORT   GPIOA
#define KEYPAD_ROW_2_PORT   GPIOA
#define KEYPAD_ROW_3_PORT   GPIOA
#define KEYPAD_ROW_4_PORT   GPIOA

// Khai báo các chân GPIO cho cột (column)
#define KEYPAD_COLUMN_1_PIN    GPIO_PIN_3
#define KEYPAD_COLUMN_2_PIN    GPIO_PIN_2
#define KEYPAD_COLUMN_3_PIN    GPIO_PIN_1
#define KEYPAD_COLUMN_4_PIN    GPIO_PIN_0

#define KEYPAD_COLUMN_1_PORT   GPIOC
#define KEYPAD_COLUMN_2_PORT   GPIOC
#define KEYPAD_COLUMN_3_PORT   GPIOC
#define KEYPAD_COLUMN_4_PORT   GPIOC

// Clock enable macro nếu cần
#define __RCC_GPIOA_KEYPAD_CLK_ENABLE() __HAL_RCC_GPIOA_CLK_ENABLE()
#define __RCC_GPIOB_KEYPAD_CLK_ENABLE() __HAL_RCC_GPIOB_CLK_ENABLE()
#define __RCC_GPIOC_KEYPAD_CLK_ENABLE() __HAL_RCC_GPIOC_CLK_ENABLE()
#define __RCC_GPIOD_KEYPAD_CLK_ENABLE() __HAL_RCC_GPIOD_CLK_ENABLE()
#define __RCC_GPIOE_KEYPAD_CLK_ENABLE() __HAL_RCC_GPIOE_CLK_ENABLE()
#define __RCC_GPIOF_KEYPAD_CLK_ENABLE() __HAL_RCC_GPIOF_CLK_ENABLE()
#define __RCC_GPIOG_KEYPAD_CLK_ENABLE() __HAL_RCC_GPIOG_CLK_ENABLE()

#endif /* KEYBOARDMATRIX_DEF_H_ */
